POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "fullName": "Abdul Hakeem",
  "email": "abdulhakeembawah@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  
  "email": "abdulhakeembawah@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3000/api/auth/logout
Content-Type: application/json

